#!/bin/bash
CHATID=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 3)
KEY=$(grep -E "^#bot# " "/etc/bot/.bot.db" | cut -d ' ' -f 2)
TIME="10"
URL="https://api.telegram.org/bot$KEY/sendMessage"
cat /etc/passwd | grep "/home/" | cut -d":" -f1 >/root/user.txt
username1=($(cat "/root/user.txt"))
i="0"
if [ -e "/var/log/auth.log" ]; then
    OS=1
    LOG="/var/log/auth.log"
fi
if [ -e "/var/log/secure" ]; then
    OS=2
    LOG="/var/log/secure"
fi
for user in "${username1[@]}"; do
    username[$i]=$(echo $user | sed 's/'\''//g')
    jumlah[$i]=0
    i=$i+1
done
cat $LOG | grep -i dropbear | grep -i "Password auth succeeded" >/tmp/log-db.txt
proc=($(ps aux | grep -i dropbear | awk '{print $2}'))
for PID in "${proc[@]}"; do
    cat /tmp/log-db.txt | grep "dropbear\[$PID\]" >/tmp/log-db-pid.txt
    NUM=$(cat /tmp/log-db-pid.txt | wc -l)
    USER=$(cat /tmp/log-db-pid.txt | awk '{print $10}' | sed 's/'\''//g')
    IP=$(cat /tmp/log-db-pid.txt | awk '{print $12}')
    if [ $NUM -eq 1 ]; then
        i=0
        for user1 in "${username[@]}"; do
            if [ "$USER" == "$user1" ]; then
                jumlah[$i]=$(expr ${jumlah[$i]} + 1)
                pid[$i]="${pid[$i]} $PID"
            fi
            i=$i+1
        done
    fi
done
cat $LOG | grep -i sshd | grep -i "Accepted password for" >/tmp/log-db.txt
data=($(ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'))
for PID in "${data[@]}"; do
    cat /tmp/log-db.txt | grep "sshd\[$PID\]" >/tmp/log-db-pid.txt
    NUM=$(cat /tmp/log-db-pid.txt | wc -l)
    USER=$(cat /tmp/log-db-pid.txt | awk '{print $9}')
    IP=$(cat /tmp/log-db-pid.txt | awk '{print $11}')
    if [ $NUM -eq 1 ]; then
        i=0
        for user1 in "${username[@]}"; do
            if [ "$USER" == "$user1" ]; then
                jumlah[$i]=$(expr ${jumlah[$i]} + 1)
                pid[$i]="${pid[$i]} $PID"
            fi
            i=$i+1
        done
    fi
done
for i in ${!username[*]}; do
    slip=$(ls "/etc/ssh/ip/" | grep -w "${username[$i]}")
    if [[ -z ${slip} ]]; then
        vmip="0"
    else
        vmip=$(cat /etc/ssh/ip/${username[$i]})
    fi
    if [ ${jumlah[$i]} -gt $vmip ]; then
        date=$(date +"%Y-%m-%d %X")
        echo "$date - ${username[$i]} - ${jumlah[$i]}"
        echo "$date - ${username[$i]} - ${jumlah[$i]}" >>/root/log-limit.txt
        exp=$(grep -wE "^### ${username[$i]}" "/etc/ssh/.ssh.db" | cut -d ' ' -f 3 | sort | uniq)
        epass=$(grep -wE "^### ${username[$i]}" "/etc/ssh/.ssh.db" | cut -d ' ' -f 4 | sort | uniq)
        limip=$(grep -wE "^### ${username[$i]}" "/etc/ssh/.ssh.db" | cut -d ' ' -f 5 | sort | uniq)
        chtml=$(grep -wE "^### ${username[$i]}" "/etc/ssh/.ssh.db" | cut -d ' ' -f 7 | sort | uniq)
        sed -i "/### ${username[$i]}/c\### ${username[$i]} $exp $epass $limip Locked $chtml" /etc/ssh/.ssh.db
        TEXT="
<b>◇━━━━━━━━━━━━━━━━━◇</b>
<b>❖ MULTI LOGIN USER ❖</b>
<b>◇━━━━━━━━━━━━━━━━━◇</b>
<b>❖ Username :</b> ${username[$i]}
<b>❖ Protokol :</b> SSH WS/OVPN
<b>❖ IP Limit :</b> ${vmip}
<b>❖ IP Login :</b> ${jumlah[$i]}
<b>◇━━━━━━━━━━━━━━━━━◇</b>
<b>Account Is 🔴LOCKED</b>
"
        echo "### ${username[$i]}" >>/etc/ssh/.mulog.db
        egrep "^${username[$i]}" /etc/passwd >/dev/null
        passwd -l ${username[$i]}
        curl -s --max-time $TIME -d "chat_id=$CHATID&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
        systemctl reload ssh
        systemctl restart udp-custom
        systemctl tunws@sochs
	fi
done
	